Project Title & Domain

Project Title: Accounts Receivable Analysis

Domain: Accounting & Finance — Accounts Receivable

Project Overview

This project focuses on analyzing accounts receivable records to understand recorded payment delays, invoice ageing, customer payment patterns, payment terms, and clearing activity. The intended outcome is to identify patterns that may help Accounts Receivable teams prioritize collection follow-ups and monitor receivables more effectively.

Business Problem

Accounts Receivable teams need reliable information about invoice due dates, recorded delays, customers, and settlement activity to monitor outstanding receivables. This project will inspect the available dataset and prepare it for later analysis of payment-delay and collection patterns.

Project Objectives

- Summarize invoice records and available ageing or delay categories.
- Examine recorded payment-delay patterns by customer and region, where the fields support the analysis.
- Compare delay patterns across payment terms and amount categories.
- Inspect document, due, and clearing dates where available and valid.
- Identify data-quality issues that may affect later analysis.

Dataset Description

- Working dataset: Account receivable analysis data set.csv
- Format: CSV
- Expected size from prior inspection: approximately 45,839 rows and 29 columns; this will be confirmed below.
- Original source URL: https://www.kaggle.com/datasets/sonalisingh1411/accounts-receivable-and-payment-delay-analysis?select=Dataset.csv
- Important limitation: Currency, row granularity, and the meanings of financial and derived fields must be confirmed before interpreting results.

Planned Analysis

After the dataset source, field definitions, and data quality have been reviewed, the later phases may include:
1. Initial data-quality review: Check missing values, exact duplicate rows, data types, and distinct values.
2. Invoice amount analysis: Summarize the recorded amount and compare the provided amount bands.
3. Delay analysis: Summarize recorded delay values and categories, after validating the meaning of the delay field.
4. Payment-term analysis: Compare delay patterns across payment-term groups.
5. Date-based analysis: Inspect document, due, posting, and clearing dates and explore trends over time where appropriate.
6. Customer-level analysis: Identify customer-level patterns using suitable aggregation and privacy-conscious reporting.
7. Visualization: Create appropriate charts and summary tables for the final report or dashboard.
The analysis will not label an invoice as currently outstanding solely from a missing clearing date until the dataset's recording rules and status logic have been confirmed.

Scope and Limitations

Project Scope
Phase 1 focuses on the proposal, loading the working CSV, and initial inspection. It includes reviewing dataset dimensions, data types, missing values, exact duplicate rows, distinct values, and the availability of relevant accounts receivable fields.

Detailed cleaning, exploratory data analysis, and final visualizations will be completed in later phases after the dataset source and field definitions are validated.

Project Limitations
1. Source not yet verified: The original source URL and data dictionary still need to be confirmed.
2. Currency and amount meaning: The currency, units, and whether Amount represents invoice value, balance, or another measure are not confirmed.
3. Field definitions: The calculation of Days_Overdue_Delay, DelayFlag, and the provided bins must be validated.
4. Historical coverage: The period represented by the file must be established from the actual dates.
5. Repeated records: A customer or document may appear more than once for valid business reasons; exact duplicates and repeated identifiers must be assessed separately.
6. Association is not causation: Any relationship found between payment terms, customer characteristics, and delays will not by itself establish cause.
7. Confidentiality: Customer names and identifiers should be masked or aggregated in public notebooks and reports where appropriate.

1. Import Required Libraries
We use Pandas for loading and inspecting the dataset, and NumPy for general numerical operations. Visualization libraries can be added in later phases when EDA and charts are required.

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

In [2]:
file_path = Path("Account receivable analysis data set.csv")

if not file_path.exists():
    raise FileNotFoundError(
        "Dataset not found. Place the CSV at 'Account receivable analysis data set.csv' "
        "inside the project folder, or update file_path to match your folder structure."
    )

df = pd.read_csv("Account receivable analysis data set.csv")
print("Dataset loaded successfully.")

Dataset loaded successfully.

In [3]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
df.head()

Number of rows: 45839
Number of columns: 29

,Cust_Num,Payment_Method_description,Document_No,Amount,Amount_Bins,Clearing_doc,Zipcode,Region,City,Customer_Name,Age_Of_Customer_Months,Age_Of_Customer_Year,Customer_Age_Year_Bins,Payment_Term,Payment_Term_Bins,Days_Overdue_Delay,Delay_Bins,Doc_Date,Net_Due_Date,Posting_Date,Clearing_date,No_of_orders_by_customer,Rank_of_order_by_customer,Weekday_clearing,Weekday_due,Quarter_clearing,DelayFlag,Weekday_clearnum,Weekday_due.1
0,5039221069,No Payment Method,91225035903,659903,200K+,80992136278,AX0034,AA126,AA66,AA64,155.0,12.0,10+,102,61 to 180,18,1 to 30,11/18/2014,2/28/2015,11/18/2014,3/18/2015,20,1,Wed,Sat,1,1,4,7
1,5039221069,No Payment Method,91225035904,16906,0 to 50K,80992136278,AX0034,AA126,AA66,AA64,155.0,12.0,10+,102,61 to 180,18,1 to 30,11/18/2014,2/28/2015,11/18/2014,3/18/2015,20,2,Wed,Sat,1,1,4,7
2,5039221069,No Payment Method,91225034522,24736,0 to 50K,80992134897,AX0034,AA126,AA66,AA64,155.0,12.0,10+,94,61 to 180,9,1 to 30,11/26/2014,2/28/2015,11/26/2014,03-09-2015,20,3,Mon,Sat,1,1,2,7
3,5039221069,No Payment Method,91225038274,17982,0 to 50K,80992138649,AX0034,AA126,AA66,AA64,155.0,12.0,10+,102,61 to 180,7,1 to 30,12/19/2014,3/31/2015,12/19/2014,04-07-2015,20,4,Tue,Tue,2,1,3,3
4,5039221069,No Payment Method,91225038275,86575,50K to 100K,80992138649,AX0034,AA126,AA66,AA64,155.0,12.0,10+,99,61 to 180,7,1 to 30,12/22/2014,3/31/2015,12/22/2014,04-07-2015,20,5,Tue,Tue,2,1,3,3

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45839 entries, 0 to 45838
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Cust_Num                    45839 non-null  int64
 1   Payment_Method_description  45839 non-null  str
 2   Document_No                 45839 non-null  int64
 3   Amount                      45839 non-null  int64
 4   Amount_Bins                 45839 non-null  str
 5   Clearing_doc                45839 non-null  int64
 6   Zipcode                     45839 non-null  str
 7   Region                      45839 non-null  str
 8   City                        45839 non-null  str
 9   Customer_Name               45839 non-null  str
 10  Age_Of_Customer_Months      45839 non-null  float64
 11  Age_Of_Customer_Year        45839 non-null  float64
 12  Customer_Age_Year_Bins      45839 non-null  str
 13  Payment_Term                45839 non-null  int64
 14  Payment_Term_Bins           45839 non-null  str
 15  Days_Overdue_Delay          45839 non-null  int64
 16  Delay_Bins                  45839 non-null  str
 17  Doc_Date                    45839 non-null  str
 18  Net_Due_Date                45839 non-null  str
 19  Posting_Date                45839 non-null  str
 20  Clearing_date               45839 non-null  str
 21  No_of_orders_by_customer    45839 non-null  int64
 22  Rank_of_order_by_customer   45839 non-null  int64
 23  Weekday_clearing            45839 non-null  str
 24  Weekday_due                 45839 non-null  str
 25  Quarter_clearing            45839 non-null  int64
 26  DelayFlag                   45839 non-null  int64
 27  Weekday_clearnum            45839 non-null  int64
 28  Weekday_due.1               45839 non-null  int64
dtypes: float64(2), int64(12), str(15)
memory usage: 14.7 MB

In [5]:
display(df.dtypes.rename("data_type").to_frame())

                           data_type
Cust_Num                       int64
Payment_Method_description       str
Document_No                    int64
Amount                         int64
Amount_Bins                      str
Clearing_doc                   int64
Zipcode                          str
Region                           str
City                             str
Customer_Name                    str
Age_Of_Customer_Months       float64
Age_Of_Customer_Year         float64
Customer_Age_Year_Bins           str
Payment_Term                   int64
Payment_Term_Bins                str
Days_Overdue_Delay             int64
Delay_Bins                       str
Doc_Date                         str
Net_Due_Date                     str
Posting_Date                     str
Clearing_date                    str
No_of_orders_by_customer       int64
Rank_of_order_by_customer      int64
Weekday_clearing                 str
Weekday_due                      str
Quarter_clearing               int64
DelayFlag                      int64
Weekday_clearnum               int64
Weekday_due.1                  int64

In [7]:
df.shape

(45839, 29)

In [8]:
df.dtypes

Cust_Num                        int64
Payment_Method_description        str
Document_No                     int64
Amount                          int64
Amount_Bins                       str
Clearing_doc                    int64
Zipcode                           str
Region                            str
City                              str
Customer_Name                     str
Age_Of_Customer_Months        float64
Age_Of_Customer_Year          float64
Customer_Age_Year_Bins            str
Payment_Term                    int64
Payment_Term_Bins                 str
Days_Overdue_Delay              int64
Delay_Bins                        str
Doc_Date                          str
Net_Due_Date                      str
Posting_Date                      str
Clearing_date                     str
No_of_orders_by_customer        int64
Rank_of_order_by_customer       int64
Weekday_clearing                  str
Weekday_due                       str
Quarter_clearing                int64
DelayFlag                       int64
Weekday_clearnum                int64
Weekday_due.1                   int64
dtype: object

In [9]:
df.size

1329331

Initial Description
The dataset contains 45,839 rows and 29 columns, including customer information, invoice amounts, payment terms, overdue delays, and document and clearing dates. It includes numerical, categorical, and date-related columns. Some columns may contain missing values, and date fields may require conversion to appropriate data types. Initial data inspection will help identify missing values, duplicate records, and inconsistent data types that may need to be addressed during data cleaning.